name: React app deployment

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CI: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy react app to github pages
        uses: tanwanimohit/deploy-react-to-ghpages@v1.0.1
